version: '2.4'
services:
  gpu-goe:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - type: bind
        source: /usr/users/burg/projects
        target: /projects
        bind:
          propagation: shared
      - type: bind
        source: /user/burg/data
        target: /data
        bind:
          propagation: shared
      - type: bind
        source: /usr/users/agecker
        target: /agecker
        bind:
          propagation: shared
    env_file: /usr/users/burg/.env
    runtime: nvidia
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=0
      - GPU=0
      - USER=burg
      - NB_UID=617278
      - NB_USER=burg
      - NB_GID=47162
      - NB_GROUP=ECKERLAB
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
      - CHOWN_HOME=yes
    container_name: burg-gpu-0
    shm_size: 128G
    user: root
    working_dir: /  # must be one dir above any mounted dir
  
  cpu-goe:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9999:8888"
    volumes:
      - type: bind
        source: /usr/users/burg/projects
        target: /projects
        bind:
          propagation: shared
      - type: bind
        source: /user/burg/data
        target: /data
        bind:
          propagation: shared
      - type: bind
        source: /usr/users/agecker
        target: /agecker
        bind:
          propagation: shared
    env_file: /usr/users/burg/.env
    environment:
      - DISPLAY=$DISPLAY
      - USER=BURG
      - NB_UID=617278
      - NB_USER=burg
      - NB_GID=47162
      - NB_GROUP=ECKERLAB
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
      - CHOWN_HOME=yes
    container_name: burg-cpu
    shm_size: 128G
    user: root
    working_dir: /  # must be one dir above any mounted dir